#!/bin/bash

source ./scripts/utils

__install_lib "nvim-lua" "plenary.nvim"
__install_lib "mfussenegger" "nvim-dap"
__install_lib "rcarriga" "nvim-dap-ui"
__install_lib "microsoft" "vscode-js-debug" 

(cd ./lib/vscode-js-debug && yarn install && yarn run compile)
(cd ./tests/js/jest && yarn install)
